### ISSUE TITLE
Unable to access https version of Nextcloud

### ISSUE THREAD

**Issue by Demon-tk** [linuxhandbook/tutorial-snippets#1]
Hello,

I am able to connect to my host. However, when I connect via HTTPS I receive `500 internal error` from Nginx. 

But if I access the server from HTTP I am greeted with the Nextcloud login dashboard. When I log in to the dashboard I am redirected to an HTTPS site that shows `500 internal server error`, though the URL is now `https://s1.nate.com/apps/dashboard/`

I have followed the guide from [here](https://linuxhandbook.com/install-nextcloud-docker/) to a T and am unsure where I have gone wrong. I have not edited the Nginx config (or let's encrypt config), they are currently the default from the docker images you have provided in the guide.

**Comment by avimanyu786** [comment]
Hi @Demon-tk, 

Sorry about your inconvenience. In the volumes section of the `LetsencryptCompanion` service in the docker compose file, `LCacme:/etc/acme.sh` doesn't seem quite necessary. The volume configuration: `NPcerts:/etc/nginx/certs` needs to be revised to `NPcerts:/etc/nginx/certs:rw` for the Let's Encrypt certificates(HTTPS) to work correctly.

It is advisable to follow this reverse proxy configuration instead:

https://github.com/avimanyu786/Jwilder-Nginx-With-LetsEncrypt

You can also check my reply on a [query](https://linuxhandbook.com/install-nextcloud-docker/#cove) on the guide(that you have mentioned) where I have added more details based on a test today.

Hope you are able to resolve it soon. All the best!
